version: "2.2"
services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: dockerfile
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_HOST: database
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    container_name: postgresql
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
